[workspace]
resolver = "2"

members = [
    "runinator",
    "runinator-models",
    "runinator-config",
    "runinator-database",
    "runinator-scheduler",
    "runinator-ws",
    
    "runinator-plugin",
    "runinator-provider-aws",
    "runinator-provider-sql",
    "runinator-plugin-console",
    "runinator-utilities",

    "command-center"
]
