[workspace]
resolver = "2"

members = [
    "runinator-models",
    "runinator-database",
    "runinator-scheduler",
    "runinator-ws",
    "runinator-worker",
    "runinator-comm",
    "runinator-importer",
    
    "runinator-plugin",
    "runinator-provider-aws",
    "runinator-provider-sql",
    "runinator-plugin-console",
    "runinator-utilities",

    "command-center"
]
