[package]
name = "runinator-ws"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
axum = "0.6"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.18", features = ["v4"] }
log-panics = "2.1"

runinator-database = { path = "../runinator-database" }
runinator-models = { path = "../runinator-models" }
runinator-comm = { path = "../runinator-comm" }
runinator-utilities = { path = "../runinator-utilities" }
