[package]
name = "runinator-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.18", features = ["v4", "serde"] }
log-panics = "2.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

runinator-comm = { path = "../runinator-comm" }
runinator-plugin = { path = "../runinator-plugin" }
runinator-provider-aws = { path = "../runinator-provider-aws" }
runinator-provider-sql = { path = "../runinator-provider-sql" }
runinator-models = { path = "../runinator-models" }
runinator-utilities = { path = "../runinator-utilities" }
runinator-api = { path = "../runinator-api" }
runinator-broker = { path = "../runinator-broker" }
