[package]
name = "runinator-supervisor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "runinator-supervisor"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
